### ISSUE TITLE
Implement formatting support

### ISSUE THREAD

**Issue by dvc94ch** [jeapostrophe/racket-langserver#1]
I started work on this. I thought it would be rather straight forward using the pretty printer. But that doesn't reindent at all.

**Comment by MLavrentyev** [comment]
Seems like we can do this using something similar to this:
```
#lang racket/gui
(require framework)
(define t (new racket:text%))
(void (send t insert-port (current-input-port)))
(send t tabify-all)
(void (send t save-port (current-output-port) 'text))
```

Going to try this out and check if it supports various other `#lang`s and if so, will make a pr. Is there a recommended place to add this?

**Comment by jeapostrophe** [comment]
There's something similar to that implemented here:

https://github.com/jeapostrophe/racket-langserver/blob/19953f6afda5f8f6b539e88d0c6be57599a8a11f/text-document.rkt#L277

But I believe it is disabled here:

https://github.com/jeapostrophe/racket-langserver/blob/01bc4ad03e449dfbe1852a141748c3d6121a1e75/methods.rkt#L114-L115

So, those are the two places you'd want to look at

**Comment by MLavrentyev** [comment]
Oh, awesome, thanks!

**Comment by MLavrentyev** [comment]
Just wanted to quickly ask - what's the way to actually test the language server on its own with input json? It seems typing into stdin while running `main.rkt` doesn't do much. I'm working on adding some formatter stuff for this issue (and to support it for the vscode magic-racket extension as well).

**Comment by jeapostrophe** [comment]
I believe that you send the input to STDIN and you must separate them with newlines and they are JSON messages.
