### ISSUE TITLE
support formatting options

### ISSUE THREAD

**Issue by dannypsnl** [jeapostrophe/racket-langserver#112]
Link: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions

```ts
interface FormattingOptions {
	/**
	 * Size of a tab in spaces.
	 */
	tabSize: uinteger

	/**
	 * Prefer spaces over tabs.
	 */
	insertSpaces: boolean;

	/**
	 * Trim trailing whitespace on a line.
	 *
	 * @since 3.15.0
	 */
	trimTrailingWhitespace?: boolean;

	/**
	 * Insert a newline character at the end of the file if one does not exist.
	 *
	 * @since 3.15.0
	 */
	insertFinalNewline?: boolean;

	/**
	 * Trim all newlines after the final newline at the end of the file.
	 *
	 * @since 3.15.0
	 */
	trimFinalNewlines?: boolean;

	/**
	 * Signature for further properties.
	 */
	[key: string]: boolean | integer | string;
}
```

**Comment by 6cdh** [comment]
I don't know if someone uses tab for indentation. I always use "convert tab to spaces" personally.
We can respect these arguments:

- `trimTrailingWhitespace`
- `insertFinalNewline`
- `trimFinalNewlines`

**Comment by jryans** [comment]
I also don't use tabs and always convert to spaces... The [Racket style guide](https://docs.racket-lang.org/style/Textual_Matters.html#%28part._.Tabs%29) also says don't use tabs. (Perhaps someone still uses tabs anyway, but I'm guessing that's quite rare in the Racket ecosystem.)

**Comment by 6cdh** [comment]
I now understand the purpose of `tabSize` and `insertSpaces`. The formatting function always uses space indentation.
If someone use tab indentation in editor, it will look weird.

Based on the Racket style guide, maybe we can replace all tabs with spaces before formatting?

**Comment by dannypsnl** [comment]
Yes, that would be great due to the style

**Comment by 6cdh** [comment]
So we ignore the options `tabSize` and `insertSpaces`, and always use replace tabs with spaces instead?

**Comment by dannypsnl** [comment]
Yes, at least we can make a that first, if anyone wants different behavior, then make the implementation be the default setup & provides others

**Comment by dannypsnl** [comment]
If we replace `\t` with 8 spaces of line first?

**Comment by 6cdh** [comment]
Good suggestion! It feels dirty but it works.
