### ISSUE TITLE
Virtual documents without file paths

### ISSUE THREAD

**Issue by jryans** [jeapostrophe/racket-langserver#122]
Some editors (at least VS Code) support "virtual" documents which are not saved anywhere on the filesystem. These include things like unsaved documents, notebook cells, etc. These virtual documents have some non-`file` URI scheme.

The language server currently assumes it is always working a document from the filesystem, as various components try to load the file from disk, split the path for directory traversal, etc. It would be great if the language server could be updated to work entirely from the document contents provided by the client without assuming it is stored in a filesystem somewhere.

As a workaround, the editor client can write these virtual documents to a temporary file and provide that to language server instead, but it would be much better to remove the filesystem requirement from the server entirely.

**Comment by dannypsnl** [comment]
Didn’t know how DrRacket handle this?

**Comment by 6cdh** [comment]
DrRacket doesn't need the file path. It doesn't needs to know the path if no relative path `require`, it only needs current working directory if there is relative path `require`.

**Comment by 6cdh** [comment]
I saw the notebook document uri looks like this:
`vscode-notebook-cell:/home/lcdh/dots/work/racket-langserver/test.ipynb#W0sZmlsZQ%3D%3D`

A simple fix could be
1. remove all `uri-is-path?` guards
2. make `uri->path` support not only file uri

**Comment by dannypsnl** [comment]
Do you think introduce a virtual filesystem for **vscode-notebook-cell** will work? It's still have path, just different from default filesystem.

**Comment by dannypsnl** [comment]
Because we can load syntax first and no provide path to `make-traversal`[^1], and hence, we can have self-maintained filesystem that be distinguished by internal tags.

[^1]: https://docs.racket-lang.org/drracket-tools/Accessing_Check_Syntax_Programmatically.html#%28def._%28%28lib._drracket%2Fcheck-syntax..rkt%29._make-traversal%29%29

**Comment by 6cdh** [comment]
> Do you mean support any URI (even for unsaved documents that have no file path at all), or only the subset like notebook cells, where there is something like a file path that could be extracted...?

It's not any URI contains a file path. But it's not important, as the code never reads the current file, it only reads the other files it rely on. For example, a test in `tests/textDocument/formatting.rkt` specify a uri `file:///test.rkt` that is not exist, but it works as it doesn't rely on other files.

We only need to make sure we know its path or hypothetical path if there is a relative `require` in the document.
When this happens, this information can only be conveyed by URI or current workspace.
So we can just try to extract a path from the URI. It never fails so we can't fallback to current workspace.

It's not easy to replace all path with uri in the code. There are many places where assume the source of document is a path. I tried it today but can't make this change easily.

VFS is an ideal solution especially if we have, say https, ssh URI in the future. But it means more work than the simple fix. And probably no one will have these problems and report them in recent years.

**Comment by 6cdh** [comment]
I made a change: https://github.com/6cdh/racket-langserver/tree/remove-uri-limit

But I can't get it work with notebooks, it seems to require extra config in the extension.

please try this commit.

**Comment by jryans** [comment]
> I made a change: [6cdh/racket-langserver@`remove-uri-limit`](https://github.com/6cdh/racket-langserver/tree/remove-uri-limit?rgh-link-date=2023-09-07T01%3A16%3A31Z)

Ah wow, seems like a clever approach! 😄 

> But I can't get it work with notebooks, it seems to require extra config in the extension.

Yes, there are several additional steps:

1. You have to install [IRacket](https://docs.racket-lang.org/iracket/) to get VS Code notebook to support Racket cells
2. The extension needs to be changed to remove the [`file` scheme filter](https://github.com/Eugleo/magic-racket/blob/30d8332e3171e82d9812818f81e9c1d222936c15/src/extension.ts#L56)

I've done these things locally and tested it with your langserver branch, and overall it solves the file path issue, so that's great! 😄 

Unsaved files now work as expected (once you manually mark them as Racket files).

For notebook cells, the langserver does run (which is the focus of this issue), but you then quickly encounter a separate problem that IRacket doesn't really want the notebook cell to have `#lang`, but the langserver requires it to be there. Anyway, resolving that seems like a separate issue.

@6cdh, I'd recommend submitting a PR with your langserver branch. Thanks for working on this! 😄
