### ISSUE TITLE
Shebang at the top of the file breaks syntax highlighting

### ISSUE THREAD

**Issue by nishanthkarthik** [jeapostrophe/racket-langserver#123]
I use racket with racket-langserver using the LSP plugin in Kate editor. Shebang at the top of the file breaks syntax highlighting. The colored parentheses come from a different kate addon.

**with shebang**
![image](https://github.com/jeapostrophe/racket-langserver/assets/7759435/aea19565-031d-427a-9949-eea11ff26b09)

**without shebang**

![image](https://github.com/jeapostrophe/racket-langserver/assets/7759435/ad8508b4-b127-43a0-a38f-dcf787b47c9e)

**Comment by 6cdh** [comment]
This lsp server doesn't support syntax highlight.
It should be the issue of Kate.

The `#!/` starts a line comment, but can be continued to the next line by ending with `\`. The bug could be from the incorrect regex.

**Comment by nishanthkarthik** [comment]
gotcha, I'll check ksyntaxhighlighting then :)
