### ISSUE TITLE
require/typed marked as "unused require"

### ISSUE THREAD

**Issue by mode89** [jeapostrophe/racket-langserver#128]
Hi :)

In `typed/racket`, `require/typed` and `unsafe-require/typed` marked as `unused require`, even though all of the imported definitions are actually referenced by the current file.

Here is an example code:
```racket
#lang typed/racket

(require typed/racket/unsafe)

(unsafe-require/typed ffi/unsafe
  [#:opaque Pointer cpointer?])

(require/typed glfw3
  [glfwCreateWindow (-> Integer Integer String Pointer Pointer Pointer)])

(glfwCreateWindow 640 480 "My Window" (assert #f cpointer?) (assert #f cpointer?))
```

**Comment by dannypsnl** [comment]
These are raised from drracket, and actually need typed-racket provide reference information, cannot be fixed here.

**Comment by mode89** [comment]
> These are raised from drracket

I use neovim and vim/ale.

**Comment by 6cdh** [comment]
This project uses drracket's library for diagnosis, so we can't fix it here. It should be reported to drracket. Sorry for the inconvenience.

**Comment by mode89** [comment]
Oh, I see. Thanks :)

**Comment by mode89** [comment]
By the way, is there any way of disabling a warning on a specific line, perhaps through inline comments, like in pylint?

**Comment by 6cdh** [comment]
no
