### ISSUE TITLE
What is the relationship between the racket-langserver and racket-language-server?

### ISSUE THREAD

**Issue by spdegabrielle** [jeapostrophe/racket-langserver#129]
What is the relationship between the racket-langserver and racket-language-server?

* `racket-language-server` was [archived in 2022](https://github.com/theia-ide/racket-language-server) but has [documentation](https://docs.racket-lang.org/racket-language-server/index.html) on docs.racket-lang.org

* `Racket-langserver` is active, but lacks documentation on docs.racket-lang.org

I believe the documentation for the archived project will confuse Racket users into thinking there is no active LSP for Racket.

Having a name that is indistinguishable to the casual browser probably makes the confusion worse.

https://github.com/theia-ide/racket-language-server 

https://docs.racket-lang.org/racket-language-server/index.html

**Comment by spdegabrielle** [comment]
@dvc94ch would appreciate your thoughts.

**Comment by dvc94ch** [comment]
the goal of the theia racket language server was supporting racket dsl's too. don't remember the details as it's been 6y

**Comment by spdegabrielle** [comment]
> the goal of the theia racket language server was supporting racket dsl's too. don't remember the details as it's been 6y

If it is not maintained should it be removed from the racket package catalog?

https://pkgs.racket-lang.org/package/racket-language-server

**Comment by dvc94ch** [comment]
Don't really care
