### ISSUE TITLE
How to launch the server from CLI?

### ISSUE THREAD

**Issue by Eugleo** [jeapostrophe/racket-langserver#13]
Sorry if this isn't relevant to this project, but how do I actually launch the server, without explicitly running `racket path/to/main.rkt`? I haven't use `raco` in a very long time, but I'd expect that after `install` it would link the executable and put it somewhere on my PATH.

**Comment by cfinegan** [comment]
I think the best way to do this is to use `racket --lib racket-langserver`. That's how [atom-idea-racket](https://github.com/cfinegan/atom-ide-racket/blob/master/index.js) starts the server from within Atom. This assumes that `racket-langserver` is installed as a collection on your system, which it won't be if you just used `git clone` to download it.

I think you can use `raco pkg install --link path/to/langserver` to "register" a directory with `raco` as a collection. `raco` can infer the name of the collection from the `info.rkt` within.
