### ISSUE TITLE
Wrong comment character in rhombus / shplait.

### ISSUE THREAD

**Issue by TimWhiting** [jeapostrophe/racket-langserver#136]
Rhombus and Shplait use C style comments `//`. Unfortunately, using the commenting out shortcut `Cmd + /` in VSCode inserts Racket comments `;`.

**Comment by dannypsnl** [comment]
I'm not sure how VSCode dealing with this, but from my understanding this project didn't provide functional about insert comment. Maybe you can also report to https://github.com/Eugleo/magic-racket

**Comment by TimWhiting** [comment]
Submitted a report there. Also, it looks like VSCode only supports declarative rules for comment characeters.
