### ISSUE TITLE
Why is libgdk required to run this language server?

### ISSUE THREAD

**Issue by Congee** [jeapostrophe/racket-langserver#18]
libgdk is required by gui-lib. I'm trying to use this project with vim inside a headless linux box and the command complains 😕 

```txt
~/dev/schemer$ racket --lib racket-langserver
ffi-lib: couldn't open "libgdk-x11-2.0.so.0" (libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory)
  context...:
   /usr/share/racket/collects/ffi/unsafe.rkt:131:0: get-ffi-lib
   "/usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/utils.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   for-loop
   [repeats 1 more time]
   run-module-instance!
   for-loop
   [repeats 1 more time]
   run-module-instance!
   do-dynamic-require
   "/usr/share/racket/pkgs/gui-lib/mred/private/wx/platform.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   ...
```
I just don't understand why libgdk is required. It seems I have to install gtk, is there a workaround?

**Comment by Congee** [comment]
OMG, after I installed libunique and libgtk, it tries to connect to a display server.
```
Unable to init server: Could not connect: Connection refused
Gtk initialization failed for display ":0"
```

bye bye racket language server 😐

**Comment by jeapostrophe** [comment]
The server works by running a headless version of DrRacket and many of DrRacket's features aren't available without its drawing libraries. It is very unfortunate.

**Comment by Congee** [comment]
Fine, thank you for your work

**Comment by stereobooster** [comment]
Is it possible to run with xvbf? I want to run it in docker? https://github.com/stereobooster/racket-vscode-remote-development-template
