### ISSUE TITLE
General errors vs errors in current file

### ISSUE THREAD

**Issue by Lazerbeak12345** [jeapostrophe/racket-langserver#23]
If one has a file, "A" and imports a file "B" and file "B" has an error on a specific line number (such as, say, an unbound identifier) that error shows up _in the current file_ at the line number of that error.

I propose that errors that are not in the current file should be a _general_ error.

**Comment by jeapostrophe** [comment]
That's a good idea

**Comment by Runi-c** [comment]
I can't reproduce this on the current version. @jeapostrophe Might be safe to close.

**Comment by jeapostrophe** [comment]
Thanks!
