### ISSUE TITLE
status on complete/WIP features?

### ISSUE THREAD

**Issue by jsomedon** [jeapostrophe/racket-langserver#4]
I'm really excited to see that racket has LSP implementation! Questions:

1. What features are completed and what are WIP? Particularly features listed on implementation list on [official page](https://langserver.org/#implementations-server):

- [ ] Code completion
- [ ] Hover
- [ ] Jump to def
- [ ] Workspace symbols
- [ ] Find references
- [ ] Diagnostics
- [ ] Automatic dependency management
- [ ] No arbitrary code execution
- [ ] Files Extension
- [ ] SymbolDescriptor Extension

2. Talking about LSP's official page, is this project not listed on official list because it's still in early stage?

**Comment by dvc94ch** [comment]
For racket lsp to be useful it needs a few custom RPC's so your question is not really that relevant... I'm mainly interested in a `racket/indentLine` rpc, initial implementation + support for theia ide can be found in [0] and [1]. Next on my list to implement is support coloring based on dr racket's color lexers. Also planning on reviewing the diagnostics code, which I haven't gotten around to yet. Also adding some diagram related rpc's like `diagram/listSupportedDiagrams` and `diagram/getModelForDiagram` are on my todo list to enable these sorts of things [2]
[0] https://github.com/theia-ide/theia-racket-extension/blob/master/racket/src/browser/racket-client-contribution.ts#L35
[1] https://github.com/theia-ide/racket-language-server/blob/master/racket-methods.rkt#L10
[2] https://www.youtube.com/watch?v=S8WCwwfHDfU

**Comment by jsomedon** [comment]
Totally understand that not all features make sense in racket's context, I was just curious to know more about current status of this project. Thanks!
