### ISSUE TITLE
Exception thrown in textDocument/signatureHelp

### ISSUE THREAD

**Issue by jackfirth** [jeapostrophe/racket-langserver#41]
I'm using VSCode with Magic Racket and occasionally seeing this error:

> Caught exn in request "textDocument/signatureHelp"
> drop: contract violation
>   expected: a (possibly improper) list with at least 1 pairs
>   given: #f
>   context...:
>    /Users/jackfirth/Library/Racket/8.0/pkgs/racket-langserver/docs-helpers.rkt:44:0: get-docs-for-tag
>    /Users/jackfirth/Library/Racket/8.0/pkgs/racket-langserver/text-document.rkt:161:0: signatureHelp
>    /Applications/Racket v8.0/collects/racket/contract/private/arrow-val-first.rkt:486:18
>    /Users/jackfirth/Library/Racket/8.0/pkgs/racket-langserver/methods.rkt:26:0: process-message
>    /Applications/Racket v8.0/collects/racket/contract/private/arrow-val-first.rkt:486:18
>    /Users/jackfirth/Library/Racket/8.0/pkgs/racket-langserver/main.rkt:54:2: consume

Haven't narrowed down the precise steps to trigger it yet, but it seems to happen pretty often.

**Comment by jeapostrophe** [comment]
@Runi-c Can you protect these `drop` s?
