### ISSUE TITLE
Format on save hangs forever

### ISSUE THREAD

**Issue by ryanslade** [jeapostrophe/racket-langserver#47]
With the latest release, format on save seems to hang forever and I see this: 

<img width="471" alt="Screenshot 2021-04-07 at 09 23 21" src="https://user-images.githubusercontent.com/25610/113826853-ee085c00-9782-11eb-8d45-74f2fb4720bb.png">

**Comment by jeapostrophe** [comment]
I wonder if this is a symptom of the response intermixing error that was fixed this morning. Would you mind updating and confirming?

**Comment by ryanslade** [comment]
I haven't seen this since updating so I'll close for now and re-open if I see it again at some point.
