### ISSUE TITLE
Missing or invalid #lang line error for custom #lang

### ISSUE THREAD

**Issue by jackfirth** [jeapostrophe/racket-langserver#49]
When I open files written in `#lang resyntax/testing/refactoring-test` ([example](https://github.com/jackfirth/resyntax/blob/master/default-recommendations/conditional-shortcuts-test.rkt)) I get the error "Missing or invalid #lang line" pointing at the `#lang` line. Based on [this code](https://github.com/jeapostrophe/racket-langserver/blob/b13132e284af977c3a7f6375e76e05f9134a796b/check-syntax.rkt#L101) it seems to be because my `#lang` implementation doesn't define an indenter. Yet DrRacket indents it using the default racket indenter just fine. Is this a bug in the langserver?

**Comment by jeapostrophe** [comment]
Yes, I think you're right. I think that the `'missing` case is not very useful and we should instead just use the default

**Comment by Runi-c** [comment]
The `'missing` case was already there, but I think I misunderstood its purpose and used it also for the cases when the #lang line truly was missing or referred to a module that doesn't exist, as the langserver previously crashed in these circumstances. This should be a simple fix - I'll just have the error handlers return a special value which should indicate an error, & use the default indenter if `read-language`'s error-thunk is called
