### ISSUE TITLE
check-syntax is slow

### ISSUE THREAD

**Issue by dvc94ch** [jeapostrophe/racket-langserver#6]
For now I'm disabling check-syntax, it solves the syntax coloring speed issue. Should probably run in a separate thread.

**Comment by dvc94ch** [comment]
Ripped out all the threading code from main. The new strategy is starting a worker thread, io channels when a document is opened. updating the document pushes a new (path src) tuple to the channel. The worker thread runs in a loop (pop all elements from queue till empty; check syntax on last element from queue). When getting a build-trace for a document in a request it will pop  all build-traces from the output queue and use the last one for computing it's result.
FYI I'm not sure if I'll be contributing my changes back, since the architecture is so different I started from scratch and copied the procedures that I needed.

**Comment by cfinegan** [comment]
Is there some place I can view these changes? i'm having trouble discerning what your implementation does differently, other than open a new thread for each document.

**Comment by dvc94ch** [comment]
So what do you think? I hope it's easier to read, maintain and extend and not just "different".

**Comment by cfinegan** [comment]
I don't have a strong opinion on the code organization, but I'm hesitant to throw everything out and start over unless there's a specific reason for doing so.

I'm curious what your use case is that's causing you to experience unacceptably low performance. I've done most of the testing in Atom so far, and the largest single racket file I've used is around 500 lines, but in my experience the performance was fine (or at least similar to what I'm used to with DrRacket). 

It sounds like your issue is more specifically that the worker thread is naively set up so that a heavyweight process (syntax check) is holding up lightweight process (syntax color). Is this a fair assessment? I'd be very interested in modifying our threading code to rectify this issue, but I would hope that we could do so without having to throw out the whole project and start over.

**Comment by dvc94ch** [comment]
Well yes that was the main issue. Also it runs syntax-check on every keystroke leading to longer and longer delays in the feedback loop.

**Comment by cfinegan** [comment]
Currently the threading code is designed mitigate the issue you are referencing by discarding syntax checks some of the keytrokes. Under the current scheme, if (for example) five _didChange_ notifications are received in a sufficiently short period of time, then the server will execute syntax checks for the first and the last of the _didChange_ notifications, but will skip syntax checks for the intermediate three notifications. So regardless of how quickly the document is edited, there should only ever be at most two outstanding syntax checks that need to complete. 

We might be able to get this down from two outstanding checks to one outstanding check if we modify the threading code to cancel in-progress syntax checks when they become redundant, but I thought that our relatively naive methodology was reasonably close to the performance one would get in DrRacket when I tested it in Atom.

**Comment by dvc94ch** [comment]
For some reason I had performance problems when trying to add indentation and coloring notifications. For those to be perceivable we are talking about ms. (coloring lagging two-three chars behind and that sort of stuff). I was able to solve those issues in my implementation. For now I'm mainly experimenting with those two features. Semantic coloring for example suffers from flickering issues at the moment.

**Comment by cfinegan** [comment]
I'm happy to consider any improvements to the threading code originating from your fork. However, I am having difficulty getting your version of the server to run on my machine. It crashes with the following error:

```
class*: superclass does not provide an expected method for override
  override name: syncheck:add-text-type
  class name: build-trace%
  context...:
   /home/conor/racket/racket/collects/racket/private/class-internal.rkt:4610:0: obj-error35
   /home/conor/racket/racket/collects/racket/private/class-internal.rkt:2270:13: get-indices
   /home/conor/racket/racket/collects/racket/private/class-internal.rkt:2096:0: compose-class
   /home/conor/racket-language-server/lang/check-syntax.rkt: [running body]
   /home/conor/racket-language-server/lang/workspace.rkt: [traversing imports]
   /home/conor/racket-language-server/main.rkt: [traversing imports]
```

Regarding the license, we're using the same license as Racket, which you can find [here](http://download.racket-lang.org/license.html) and is based on LGPL.

**Comment by dvc94ch** [comment]
Isn't racket moving to apache + mit licenses?

Which version of racket are you using? That seems like your version is too old or too new. I'm using 6.12 currently.
