### ISSUE TITLE
Unable to get document for symbols imported from `racket`

### ISSUE THREAD

**Issue by shenlebantongying** [jeapostrophe/racket-langserver#72]
For example: if you hover over `define` and the langserver will redirect you to this link  which is 404

<https://docs.racket-lang.org/racket/reference/define.html#(form._((lib._racket/private/base..rkt)._define))>

The working link now is:
<https://docs.racket-lang.org/reference/define.html#(form._((lib._racket/private/base..rkt)._define))>

There is no `racket` between `docs.racket-lang.org` and `define.html#`

Maybe some work can be done on the website side,

The hover-to-read-doc was added on: https://github.com/jeapostrophe/racket-langserver/pull/33 by @Runi-c

**Comment by flagpoonage** [comment]
Not a solution to the problem, but I used a Redirector plugin for Firefox to make this not an issue for me:
https://addons.mozilla.org/en-US/firefox/addon/redirector/

I assume there's something similar for Chrome or other browsers.

![Screenshot from 2021-12-18 14-13-24](https://user-images.githubusercontent.com/7937480/146631443-cdba9515-0cf3-454f-b3a2-6159365adc8a.png)
