### ISSUE TITLE
Server requires #lang line even though #reader is present.

### ISSUE THREAD

**Issue by jlefkoff** [jeapostrophe/racket-langserver#86]
By default, opening a file created in DrRacket in VSCode throws the error `Missing or invalid #lang line` from `define lang-diag` as seen in `check-syntax.rkt`. However this file compiles and runs just fine. Below is an example of the first three lines inserted by DrRacket.

```
;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname 1-family) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
```

**Comment by dannypsnl** [comment]
Because this project open file with `racket:text%` class, the class requires the language file must have `#lang` line, so it would only accidentally work for non-racket language (I know it sounds weird)
