### ISSUE TITLE
please add the 'racket' topic

### ISSUE THREAD

**Issue by spdegabrielle** [jeapostrophe/racket-langserver#9]
not your first rodeo :)

**Comment by jeapostrophe** [comment]
Ugh... I wish there were a way to quickly add this to me 100+ repos.

**Comment by spdegabrielle** [comment]
Sorry I’m so annoying - trying to raise the discoverability of Racket - I keep coming across great code that isn’t tagged. And github isn’t great at detecting the language.

**Comment by spdegabrielle** [comment]
@jeapostrophe https://github.com/github/explore/issues/908
